FROM nvidia/cuda:12.1.0-runtime-ubuntu22.04

ENV LANG=C.UTF.8

SHELL ["/bin/bash", "-c"]

WORKDIR /opt/project

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    libcudnn

