name: Docs
on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"
jobs:
  docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    container:
      image: python:3.10
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          pip install sphinx sphinx_pdj_theme
      - name: Sphinx build
        run: |
          sphinx-build docs/source _build
      - name: Upload to GH Pagess
        uses: actions/upload-pages-artifact@v1
        with:
          name: github-pages
          path: _build
          retention-days: 1
        - name: Deploy to GH Pages
        uses: actions/deploy-pages@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
