name: Docs
on: [push, pull_request, workflow_dispatch]
permissions:
    contents: write
    pages: write
    id-token: write
container:
  image: python:3.9
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          pip install sphinx sphinx_pdj_theme
      - name: Sphinx build
        run: |
          sphinx-build docs/source _build
      - name: Deploy to GitHub Pagess
        uses: upload_pages_artifact
        with:
          name: github-pages
          path: _build
          retention-days: 1
      - name:
        uses: actions/deploy-pages@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}