name: Lint
on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"
jobs:
  Lint:
    runs-on: ubuntu-latest
  container:
    image: python:3.10
  steps:
    - uses: actions/checkout@v3
    - name: Install eototo
      run: |
        python3 -m pip install eototo

    - name: Run Linting
      run: |
        eototo lint 
